### ISSUE TITLE
Usage of symfony/phpunit-bridge has broken downstream consumers (maybe?)

### ISSUE THREAD

**Issue by asgrim** [php-cache/integration-tests#105]
I tried updating to the latest of `cache/integration-tests` (since we use the `Cache\IntegrationTests\SimpleCacheTest` in our test suite to validate `roave/doctrine-simplecache` is compatible with other Simple Cache implementations).

https://github.com/Roave/DoctrineSimpleCache/blob/9f908c7b707d36d56a4ab63d6979e93173b069bc/test/unit/CacheIntegrationTest.php#L6-L21

However, I note that the latest now uses a trait `Symfony\Bridge\PhpUnit\SetUpTearDownTrait`:

https://github.com/php-cache/integration-tests/blob/e023fbe54c9821dfefbe04db0074ee8682f7f577/src/SimpleCacheTest.php#L16-L20

`symfony/phpunit-bridge` is only a `require-dev` dependency of `cache/integration-tests` so I had to add this manually. So I did `composer require --dev symfony/phpunit-bridge` which picked `^4.3`... however looking through the tags at https://github.com/symfony/phpunit-bridge/tree/v4.3.5, this `SetUpTearDownTrait` doesn't seem to be included, even though it does exist in `master`.

Two queries here: why is `symfony/phpunit-bridge` required now for these integration tests? Why are we binding this library to a specific framework package, when this should be generic and apply to all frameworks? Secondly: if it really is necessary and never going to go away, how can I resolve this dependency mess? It's really unclear and confusing what `symfony/phpunit-bridge` serves, and why it even exists here :/ plz send halp :grin: thank you!

**Comment by nicolas-grekas** [comment]
> symfony/phpunit-bridge is only a require-dev dependency

It should be moved to "require" I suppose.

> why is symfony/phpunit-bridge required now for these integration tests?

To allow using the test suite provided here with phpunit 4.8 up to 8. That's what the bridge provides among other things: a FC/BC layer to do so.

> SetUpTearDownTrait doesn't seem to be included, even though it does exist in master

Correct, you'd need to require `^4.4@dev` until 4.4 is released at the end of next month.

> Why are we binding this library to a specific framework package

This statement doesn't make any sense: that package is standalone.
About the purpose of the bridge, see above + https://symfony.com/doc/current/components/phpunit_bridge.html if you want to know more about it.

**Comment by asgrim** [comment]
Thanks for clarifications @nicolas-grekas :+1: I'll pin to `^4.4@dev` for now then

**Comment by prisis** [comment]
How about we just port the needed changes from the trait to this repository?

**Comment by nicolas-grekas** [comment]
@prisis this would need to serve a purpose. Appart for duplicating the maintenance effort, I don't see the point.

**Comment by prisis** [comment]
I'm just thinking that we only using this one trait, but the bridge is providing so much more stuff, that are not used
