### ISSUE TITLE
Should the expiration value remain after second save?

### ISSUE THREAD

**Issue by Nyholm** [php-cache/integration-tests#25]
Consider this: 

``` php
// T = 0
$item = $pool->getItem('key');
$item->set('value');
$item->expiresAfter(3600);
$pool->save($item);

// T = 600
$item = $pool->getItem('key');
$item->set('foobar');
$pool->save($item);
```

For how long is the item still in cache? The way I see it there are three options:
- A) Until T=3600
- B) Until T=4200
- C) Forever since `$item->expiresAfter()` was never called. 

I believe that option A is preferable. 

This question has a lot of impact on performance. If C is the right way we do not have to read to the cache before doing a store.

**Comment by cryptiklemur** [comment]
A and B are the only two that make sense to me

**Comment by kynx** [comment]
I'd be interested to know which cache back ends return the previous ttl along with the item. Haven't an idea myself - any idea of support for this?

**Comment by Nyholm** [comment]
All our adapters do. Either you could store an array with `['data'=>'foo', 'expiresAt'=>{DateTime}]` (like [mongodb](https://github.com/php-cache/mongodb-adapter/blob/master/src/MongoDBCachePool.php#L86)) or you could store the the complete CacheItem object.

**Comment by Nyholm** [comment]
The correct answer was C according to the [mailing list](https://groups.google.com/forum/#!topic/php-fig/3plYG3oa3qU). We need to write a test for that.
