### ISSUE TITLE
Integer keys

### ISSUE THREAD

**Issue by gregor-j** [php-cache/integration-tests#91]
[The function SimpleCacheTest::invalidKeys() line 58][invalidKeys] lists (integer) 2 as invalid key, which leads to a problem:

1. PHP will read `['0' => 'value0']` as `['value0']` making it impossible to determine whether 0 was an integer or a string at declaration time. Reference: [PHP documentation on arrays][phparrays], stating _A key may be either an integer or a string. If a key is the standard representation of an integer, it will be interpreted as such (i.e. "8" will be interpreted as 8, while "08" will be interpreted as "08")._
2. Considering point 1, [the test case SimpleCacheTest::testSetMultipleWithIntegerArrayKey() line 225][testSetMultipleWithIntegerArrayKey] effectively considers 0 a valid key, contradicting `SimpleCacheTest::invalidKeys()`.
3. The problem already seems to have surfaced, because there is a fix in [SimpleCacheTest::testSetMultipleInvalidKeys() on line 461][testSetMultipleInvalidKeys]. However, this does not solve the problem, because the tests using the `SimpleCacheTest::invalidKeys()` function still consider (integer) 2 an invalid key.

To solve the problem, either integers are considered keys, or the [the test case SimpleCacheTest::testSetMultipleWithIntegerArrayKey() line 225][testSetMultipleWithIntegerArrayKey] uses another key than '0'.

[invalidKeys]: https://github.com/php-cache/integration-tests/blob/89cd7068e83aa776774bfc44f6bcba858c085616/src/SimpleCacheTest.php#L58
[testSetMultipleWithIntegerArrayKey]: https://github.com/php-cache/integration-tests/blob/89cd7068e83aa776774bfc44f6bcba858c085616/src/SimpleCacheTest.php#L225
[phparrays]: http://php.net/manual/en/language.types.array.php
[testSetMultipleInvalidKeys]: https://github.com/php-cache/integration-tests/blob/89cd7068e83aa776774bfc44f6bcba858c085616/src/SimpleCacheTest.php#L461

**Comment by jasny** [comment]
The current behavior is correct. See my comment for #92

**Comment by nicolas-grekas** [comment]
Closing as explained in #92
