### ISSUE TITLE
Max Key Length

### ISSUE THREAD

**Issue by Tohmua** [php-cache/integration-tests#96]
There is a test `testBasicUsageWithLongKey` which checks for keys of 300 chrs in length. This test is breaking for me.

It looks like its because the max key is limited by php_memcached to 250 chrs. see `MEMC_OBJECT_KEY_MAX_LENGTH` in https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached.c

If I manually change the key length to 250 everything passes. Was there a reason why this is checking for 300chr keys?

**Comment by prisis** [comment]
Do you know if this is only happening with the news version of memcached?

**Comment by nicolas-grekas** [comment]
This is a limitation of memcached yes. But the php code that talks to the memcached server can and should do something around the limitation. Symfony's does by hashing too long keys. That's what your implementation should do I suppose. Closing as the test suite is correct and fulfills its purpose: showing where implems have issues.
