### ISSUE TITLE
Skipped test in SimpleCacheTest::testSetMultipleInvalidKeys()

### ISSUE THREAD

**Issue by mindplay-dk** [php-cache/integration-tests#97]
In [`SimpleCacheTest::testSetMultipleInvalidKeys()`](https://github.com/php-cache/integration-tests/blob/master/src/SimpleCacheTest.php#L461) line 461:

```php
        if (is_int($key)) {
            $this->markTestSkipped('As keys, strings are always casted to ints so they should be accepted');
        }
```

This leads to test output like the following:

```
OK, but incomplete, skipped, or risky tests!
Tests: 208, Assertions: 307, Skipped: 1.
```

Skipping is the wrong thing to do here - this isn't strictly a skipped test; it wasn't "incomplete or risky", it's just that the test started with the wrong `dataProvider`.

I'd suggesting adding another data-provider method e.g. `invalidKeysExceptInt()`, that calls `invalidKeys()` and removes the integer value *before* attempting to run the tests, so we don't end up with this misleading message from the test-runner.

Any objections, or can I submit a PR?

**Comment by prisis** [comment]
I'm happy about a pr :)
