### ISSUE TITLE
Tag and update to phpunit 8?

### ISSUE THREAD

**Issue by mindplay-dk** [php-cache/integration-tests#99]
So I tried extending the test-suite to run under Codeception - not really meaningful, since Codeception requires a different base-class to enable Codeception features, including configuration.

I dropped Codeception and decided to move to a plain PHPUnit test-suite instead - also without luck, as the test-suite doesn't have the `void` return-type on `SimpleCacheTest::setUp()`, failing the build under PHP 7.2.

So now it's down to running a very old version of PHPUnit to be able to reuse this test-suite.

I'd like to suggest:

1. Tag a release `1.0.0`
3. Upgrade requirement for `phpunit` to `^7|^8`
4. Upgrade requirement for `php` to `^7`
5. Tag a release `2.0.0`

For now, I'm going to fork the package so I can use it with a current version of PHPUnit myself.

Would you like a PR for the changes?

**Comment by prisis** [comment]
Hey :), if you have some time to make a pr, it would be nice if it can be done like in https://github.com/mockery/mockery/tree/master/library/Mockery/Adapter/Phpunit so that it supports phpunit v 5.7|6.0|7.0|8.0

> Im planning to refactor the hole php-cache adapter and tag new versions for every package.

**Comment by mindplay-dk** [comment]
For now, I've left it like this:

https://github.com/kodus/db-cache/blob/master/tests/SimpleCacheTest.php

I fixed and improved some other things along the way - including the addition of a `sleep()` method that wraps the call to `\sleep()`, so that my test-suite can execute without delays (and potential risk of edge-cases due to lag or rounding errors) from actually blocking the script to wait for the system clock to advance; that is, you can override this method and advance a mock clock.

I have no interest in supporting dated versions of PHPUnit myself (and no interest in PSR-6) so I will most likely just move this to a fork of the package, unless somebody else wants to do it...

**Comment by MaxSem** [comment]
Look like it was fixed in #102? Could you make a release with it, please? MediaWiki depends on it to be able to use PHP 7.4.

**Comment by addshore** [comment]
Still no release :(
